COLUMNS:
  GENDER: object
  AGE: int64 
  SMOKING: int64 
  YELLOW_FINGERS: int64 
  ANXIETY: int64 
  PEER_PRESSURE: int64 
  CHRONIC DISEASE: nt64 
  FATIGUE:  int64 
  ALLERGY: int64 
  WHEEZING: int64
  ALCOHOL CONSUMING: int64 
  COUGHING: int64 
  SHORTNESS OF BREATH: int64 
  SWALLOWING DIFFICULTY: int64 
  CHEST PAIN: int64 
  LUNG_CANCER: object


TARGET_COLUMN:  # output column
  name: LUNG_CANCER